import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import LoginForm from "../components/LoginForm";
import RegisterForm from "../components/RegisterForm";
import Vault from "../components/Vault";
import styles from "../styles/Home.module.css";

export interface IVaultItem {
  website: string;
  username: string;
  password: string;
}
export type TStep = "login" | "register" | "vault";

const Home: NextPage = () => {
  const [step, setStep] = useState<TStep>("register");
  const [vault, setVault] = useState<IVaultItem[]>([]);
  const [vaultKey, setVaultKey] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {step === "register" && (
          <RegisterForm setStep={setStep} setVaultKey={setVaultKey} />
        )}
        {step === "login" && <LoginForm />}
        {step === "vault" && <Vault />}
      </main>
    </div>
  );
};

export default Home;
