import { Box, Button } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import LoginForm from "../components/LoginForm";
import RegisterForm from "../components/RegisterForm";
import Vault from "../components/Vault";
import styles from "../styles/Home.module.css";

export interface IVaultItem {
  website: string;
  username: string;
  password: string;
}
export type TStep = "login" | "register" | "vault";

const Home: NextPage = () => {
  const [step, setStep] = useState<TStep>("login");
  const [vault, setVault] = useState<IVaultItem[]>([]);
  const [vaultKey, setVaultKey] = useState("");

  useEffect(() => {
    const vault = window.sessionStorage.getItem("vault");
    const vaultKey = window.sessionStorage.getItem("vk");

    if (vault) setVault(JSON.parse(vault));
    if (vaultKey) {
      setVaultKey(JSON.parse(vaultKey));
      setStep("vault");
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {step === "register" && (
          <RegisterForm setStep={setStep} setVaultKey={setVaultKey} />
        )}
        {step === "login" && (
          <LoginForm
            setStep={setStep}
            setVault={setVault}
            setVaultKey={setVaultKey}
          />
        )}
        {(step === "login" || step === "register") && (
          <Box>
            <Button
              bg="none"
              border="1px solid black"
              color="black"
              mt={10}
              onClick={() => setStep(step === "login" ? "register" : "login")}
            >
              {step === "login" ? "Register" : "Login"}
            </Button>
          </Box>
        )}
        {step === "vault" && <Vault vault={vault} vaultKey={vaultKey} />}
      </main>
    </div>
  );
};

export default Home;
